#!/bin/bash
cd ~/hsed
echo "purge ..."          && stack purge                                        && \
echo "maketags ..."       && maketags                                           && \
echo "build ..."          && stack build --haddock --haddock-arguments="-o doc" && \
echo "test ..."           && stack test                                         && \
echo "install ..."        && stack install                                      && \
echo -e "some sort of testifying here ...\n"                                    && \
echo "maketags again ..." && maketags                                           && \
echo "graphs ..."         && makegraphs                                         && \
success || failure
