#!/bin/bash
cd ~/hsed
  (2>/dev/null graphmod | tee hsed.graph     | dot -Tpdf > hsed.pdf    ) && \
  (tred hsed.graph      | tee hsedTred.graph | dot -Tpdf > hsedTred.pdf) && \
  open hsedTred.pdf && open hsed.pdf
