name:                hsed
version:             0.1.0.1
github:              scottcmarks/hsed
license:             BSD3
author:              Scott Marks
maintainer:          scott@magnolia-heights.com
copyright:           Magnolia Heights R&D

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/scottcmarks/hsed#readme>

dependencies:
- base >= 4.10 && < 10
- rio >= 0.1.1.0

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hsed-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hsed
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hsed-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hsed
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
