name:                hsed
version:             0.1.0.1
github:              scottcmarks/hsed
license:             BSD3
author:              Scott Marks
maintainer:          scott@magnolia-heights.com
copyright:           Magnolia Heights R&D

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            TCG SWG Self-Encrypting Drive library
# category:            System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/scottcmarks/hsed#readme>

dependencies:
- base >= 4.10 && < 10
- rio >= 0.1.1.0
- abnf
- array
- attoparsec
- base16-bytestring
- bytestring
- conduit
- conduit-extra
- containers
- either
- exceptions
- ghc
- ghc-prim
- githash
- heredoc
- hspec
- integer-gmp
- integer-logarithms
- lens
- megaparsec
- monad-loops
- mtl
- pretty
- regex-pcre-builtin
- singletons
- static-text
- template-haskell
- text
- transformers
- vector
- word8
- ListLike
- QuickCheck
- quickcheck-instances


ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

library:
  source-dirs: src

executables:
  hsed:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hsed
    - optparse-simple
    - cborg

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hsed-spec-test:
    main:                Spec.hs
    source-dirs:         spec-tests
    dependencies:
    - hsed

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  hsed-doc-test:
    main:                DocTest.hs
    source-dirs:         doc-tests
    dependencies:
    - hsed
    - doctest

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
