:set -Wno-type-defaults
:set prompt-cont ""

:load dev/DevMain.hs
:set -XQuasiQuotes
:set -XOverloadedStrings
:set -XDataKinds

import System.IO
putStrLn "loading script ..."
--------------------------------------------------------------------------------

import Data.ByteString(head,tail)
import Data.Either(Either(..))
import Data.Foldable(mapM_)
import Data.Functor((<$>))
import Data.Maybe(Maybe(..))
import Data.Text(cons, snoc, pack, unpack)
import GHC.Arr(range)
import GHC.Base(flip,map,pure,(.),($),(*>),(<*>),(<*),(<>))
import GHC.Classes((<))
import GHC.Err(undefined)
import GHC.Show(show)

--------------------------------------------------------------------------------

import Text.Megaparsec(parse,errorBundlePretty)
import Text.ABNF.ABNF.Parser(parseABNF)
import Text.ABNF.PrettyPrinter(prettyShow)


:{

mapM_ (putStrLn . unpack) [ "coreTypesTCGABNF =" , coreTypesTCGABNF
                          , ""
                          , "correctABNFFromTCGABNF coreTypesTCGABNF =>" , correctABNFFromTCGABNF coreTypesTCGABNF
                          ]
:}

:{
mapM_ putStrLn $ case parseABNF "~/hsed/dev/script FIXME" $ preprocessABNF coreTypesTCGABNF of
  Right rules -> [ "success"
                 , ""
                 , correctABNFToTCGABNF $ prettyShow rules
                 ]
  Left peb -> [ "failed"
              , ""
              , errorBundlePretty peb
              ]
:}

putStrLn "Buh-bye now."

--------------------------------------------------------------------------------

import GHC.Base(const, (++))
:def! $ (pure . (":! bash -l -c " ++) . show)
:def! B (pure . (":! bash -l -c \"stack build\"" ++) . show)
:def! D (pure . const (":set -ddump-splices") )
:def! H (pure . (":! bash -l -c \"./h\"" ++) . show)
:def! P (pure . (":! bash -l -c \"./hp\"" ++) . show)
:set -XDataKinds
:set -XTemplateHaskell
:set -XOverloadedStrings
import Data.Char (toUpper)



:load src/Data/SizedText/TH.hs
:load src/Data/SizedText.hs
import Data.ByteString hiding(take,length,putStrLn)
:i take
:t take $(sz "Hello")
:t take $(sz "Hello") :: C.Sized ByteString 4 32
take $(sz "Hello") :: C.Sized ByteString 4 32
length (take $(sz "Hello") :: C.Sized ByteString 4 32)
take $(sz "Hello") :: C.Sized ByteString 4 32
take $(sz "Hello") :: C.Sized ByteString 4 4
take $(sz "HelloHelloHelloHelloHelloHelloHello") :: C.Sized ByteString 4 32
:i create
:i ByteString
"Hello" :: ByteString
create ("Hello" :: ByteString) :: Maybe (C.Sized ByteString 4 32)
create ("Hello" :: ByteString) :: Maybe (C.Sized ByteString 4 32)
create ("Hello" :: ByteString) :: Maybe (C.Sized ByteString 4 4)
create ("Hello" :: ByteString) :: Maybe (C.Sized ByteString 8 32)
$(sz "Hello")


putStrLn ".. script loaded."
